version: '3'

services:
  elgalu:
    image: elgalu/selenium
    command: echo 0
    restart: "no" # ensures it does not get recreated

  dosel:
    image: dosel/zalenium
    depends_on:
    - elgalu
    command: echo 0
    restart: "no" # ensures it does not get recreated

  zalenium:
    image: dosel/zalenium
    container_name: zalenium
    depends_on:
    - dosel
    ports:
    - "4444:4444"
    restart: unless-stopped
    tty: true
    command: ["start", "--desiredContainers", "5", "--maxDockerSeleniumContainers", "10","--sauceLabsEnabled","false","--screenWidth", "1920", "--screenHeight", "1080"]
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /Users/mac/Documents/docker-volumes:/home/seluser/videos
    privileged: true
    networks:
      mynetwork:
        aliases:
        - chrome

  search-module:
    image: vinsdocker/selenium-docker
    depends_on:
    - zalenium
    environment:
    - MODULE=testng.xml

  mock:
    image: elgalu/google_adwords_mock
    depends_on:
    - zalenium
    ports:
    - 8081:8081
    tty: true
    environment:
    - MOCK_SERVER_PORT=8081

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'staging_fdbr_salon'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'serverteam'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'DDKW31Kr31'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
    # <Port exposed> : < MySQL Port running inside container>
    - '3306:3306'
    expose:
    # Opens port 3306 on the container
    - '3306'
    # Where our data will be persisted
    volumes:
    - /Users/mac/Documents/docker-volumes/database:/var/lib/mysql

networks:
  mynetwork:
    driver: bridge