version: '3'

services:
  elgalu:
    image: elgalu/selenium
    command: echo 0
    restart: "no" # ensures it does not get recreated

  dosel:
    image: dosel/zalenium
    depends_on:
    - elgalu
    command: echo 0
    restart: "no" # ensures it does not get recreated

  zalenium:
    image: dosel/zalenium
    container_name: zalenium
    depends_on:
    - dosel
    ports:
    - "4444:4444"
    restart: unless-stopped
    tty: true
    command: ["start", "--desiredContainers", "5", "--maxDockerSeleniumContainers", "10","--sauceLabsEnabled","false","--screenWidth", "1920", "--screenHeight", "1080"]
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /Users/mac/Documents/docker-volumes:/home/seluser/videos
    privileged: true
    networks:
      mynetwork:
        aliases:
        - chrome

  mock:
    image: elgalu/google_adwords_mock
    depends_on:
    - zalenium
    ports:
    - 8080:8080
    tty: true
    environment:
    - MOCK_SERVER_PORT=8080

networks:
  mynetwork:
    driver: bridge