#!/usr/bin/env groovy

pipeline {
    agent any
	tools { 
        maven 'MAVEN_HOME' 
        jdk 'JAVA_HOME' 
    }
    stages {
        stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                ''' 
            }
        }

       stage ('Build') {
            steps {
		 dir('/Users/mac/.jenkins/workspace/pipeline-script/Automation-Master') {
            sh 'mvn test'
        }
		}
         
        }
    }

        always {
            step([$class: 'Mailer',
                notifyEveryUnstableBuild: true,
                recipients: "qatestingsatu01@gmail.com",
                sendToIndividuals: true])
        }
    
}