
pipeline{
	agent any
	stages{
		stage("Pull Latest Image"){
			steps{
				sh "docker pull beserk/seleniumgrid:1.0.0"
			}
		}
		stage("Start Grid"){
			steps{
			    dir('/var/lib/jenkins/workspace/fdn.selenium-grid.docker@script/Automation-Master') {
				sh "docker-compose up -d"
				}
			}
		}

       stage ('Build') {
            steps {
		        dir('/var/lib/jenkins/workspace/fdn.selenium-grid.docker@script/Automation-Master') {
                sh 'sh healthcheck.sh'
                }
		    }
        }

		stage("Run Test"){
			steps{
				dir('/var/lib/jenkins/workspace/fdn.selenium-grid.docker@script/Automation-Master') {
                sh 'mvn test'
                }
		    }
		}
	}
	post{
		always{
			archiveArtifacts artifacts: 'output/**'
			sh "docker-compose down"
			sh "sudo rm -rf output/"
		}
	}
}